version: '3'

services:
  fast_api:
    build: ./RESTful_API
    ports:
      - "8000:8000"

  flask_app:
    build: ./SQLite_Flask
    ports:
      - "5000:5000"

  streamlit_app:
    build: ./streamlit_app
    ports:
      - "8501:8501"
